spring: 
  profiles: 
    active: 
     - dev

---
server: 
  port: 8201

spring: 
  profiles: dev
  applocation: 
    name: microservicecloud-config-client

eureka: 
  instance:
    prefer-ip-address: true
    instance-id: microservicecloud-config-client-dev
    
  client: 
    service-url: 
     defaultZone: http://eureka7001.com:7001/eureka/

---
server: 
  port: 8202

spring: 
  profiles: test
  applocation: 
    name: microservicecloud-config-client

eureka: 
  instance:
    prefer-ip-address: true
    instance-id: microservicecloud-config-client-test
  client: 
    service-url: 
     defaultZone: http://eureka7001.com:7001/eureka/
