spring: 
  profiles: 
    active: 
     - dev

---
server: 
  port: 8201

spring: 
  profiles: dev
  applocation: 
    name: microservicecloud-config-client

eureka: 
  instance:
<<<<<<< HEAD
 
    prefer-ip-address: true
 
    instance-id: microservicecloud-config-client-dev
=======
    prefer-ip-address: true
    instance-id: microservicecloud-config-client-dev
    
>>>>>>> 23e59ba918faf75fb21502dac1c32ceb73276b5b
  client: 
    service-url: 
     defaultZone: http://eureka7001.com:7001/eureka/

---
server: 
  port: 8202

spring: 
  profiles: test
  applocation: 
    name: microservicecloud-config-client

eureka: 
  instance:
<<<<<<< HEAD
 
    prefer-ip-address: true
 
    instance-id: microservicecloud-config-client-test
  client: 
    service-url: 
     defaultZone: http://eureka7001.com:7001/eureka/
=======
    prefer-ip-address: true
    instance-id: microservicecloud-config-client-test
  client: 
    service-url: 
     defaultZone: http://eureka7001.com:7001/eureka/
>>>>>>> 23e59ba918faf75fb21502dac1c32ceb73276b5b
